cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'azure-cli'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'jp2a'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'postgresql'
brew 'python'
brew 'ruby-build'
brew 'rbenv'
brew 'shpotify'
brew 'spaceman-diff'
brew 'speedtest-cli'
brew 'tmux'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask '1password'
cask 'atom'
cask 'google-chrome'
cask 'spotify'
cask 'iTerm2'
cask 'visual-studio-code'
cask 'vlc'
